# Generated by Django 4.2.5 on 2023-09-13 21:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Profile',
        ),
    ]
